### ISSUE TITLE
crawl only未联动

### ISSUE THREAD

**Issue by len0m0** [test502git/awvs14-scan#18]
1、配置文件
![image](https://user-images.githubusercontent.com/66287939/159233289-43d9d009-a043-4190-88ee-e0bfc45b846d.png)

2、
![image](https://user-images.githubusercontent.com/66287939/159233183-d6a5c3ee-f7fd-4608-8417-d7f1b44f7193.png)

**Comment by test502git** [comment]
未复现，注意config文件格式

**Comment by test502git** [comment]
未复现，请注意2点
1、config文件格式
2、awvs如果为容器安装，如果设置上级代理127.0.0.1，这时代理还是本地容器中的127.0.0.1
