### ISSUE TITLE
批量添加任务NewConnectionError错误

### ISSUE THREAD

**Issue by ENDZHT** [test502git/awvs14-scan#19]
HTTPSConnectionPool(host='192.168.248.128', port=3443): Max retries exceeded with url: //api/v1/scans (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000167C5A70610>: Failed to establish a new connection: [WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。'))

出现这个错误后，任务只能添加不会开始

**Comment by test502git** [comment]
性能不够，升配置
